config/routes.rb
Rails.application.routes.draw do
  root "articles#index"
  resources :tags, only: [ :index ]
  resources :users, only: [ :new, :create ]
  resources :sessions, only: [ :new, :create, :destroy ]
  resources :articles

  get "*path", to: "application#render_404"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
    has_many :article_tags, dependent: :destroy
    has_many :tags, through: :article_tags
    belongs_to :user

    validates :title, presence: true, length: { minimum: 5 }, uniqueness: true
    validates :about, :description, presence: true
end

app/models/article_tag.rb
class ArticleTag < ApplicationRecord
  belongs_to :article
  belongs_to :tag
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :article_tags, dependent: :destroy
  has_many :articles, through: :article_tags
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :articles, dependent: :destroy
  validates :name, presence: true
  validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :password, length: { minimum: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
  helper_method :current_user, :require_login, :logged_in?

  def render_404
    render file: "#{Rails.root}/public/404.html", layout: false, status: :not_found
  end

  private
    # 認証周りのメゾットを定義
    def current_user
      @current_user ||= User.find_by(id: session[:user_id])
    end

    def logged_in?
      !!current_user
    end

    def require_login
      unless logged_in?
        flash[:alert] = "ログインまたはユーザ登録を行なってください。"
        redirect_to new_session_path
      end
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :require_login, only: [ :new, :create, :edit, :update, :destroy ]
  before_action :set_article, only: [ :show, :edit, :update, :destroy ]
  # edit, update, destroy アクションで記事の作成者かチェック
  before_action :check_article_owner, only: [ :edit, :update, :destroy ]

  MIN_PAGE_LIMIT = 5

  def index
    @page = params[:page].to_i > 0 ? params[:page].to_i : 1
    @articles = Article.page(@page).per(MIN_PAGE_LIMIT)
  end

  def new
    @article = Article.new
  end

  def create
    tag_name_list = params[:article][:tag_string].split(',').map(&:strip)

    @article = current_user.articles.build(article_new_params.except(:tag_string))
    # タグ名を取得し、更新
    tags = tag_name_list.map do |name|
      Tag.find_or_create_by(name: name)
    end
  
    if @article.save
      @article.tags << tags
      redirect_to articles_path
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @article.update(article_new_params)
      redirect_to article_path(@article)
    else
      render :edit
    end
  end

  def destroy
    if @article.destroy
      flash[:notice] = "記事の削除が成功しました。"
      redirect_to articles_path
    else
      flash[:alert] = "記事の削除が失敗しました。"
      redirect_to article_path(@article)
    end
  end

private
  # 共通処理などはprivate内で定義
  def set_article
    @article = Article.find(params[:id])

    # 記事が見つからなかった場合の例外を捕捉し、処理を終了してからリダイレクト
    rescue ActiveRecord::RecordNotFound
      flash[:alert] = "お探しの記事は見つかりませんでした。"
      redirect_to articles_path and return
  end

  def article_new_params
    params.require(:article).permit(:title, :about, :description, :tag_string)
  end

  def check_article_owner
    unless current_user.id == @article.user_id
      flash[:alert] = "この操作を行う権限がありません。"
      redirect_to article_path(@article) and return
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: session_new_params[:email])
    # ダイジェスト化したパスワードで判定
    if user && user.authenticate(session_new_params[:password])
      session[:user_id] = user.id
      flash[:notice] = "ログインが成功しました。"
      redirect_to articles_path
    else
      flash.now[:alert] = "ログインが失敗しました。"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "ログアウトしました。"
    redirect_to articles_path
  end

  private
  def session_new_params
    params.require(:session).permit(:email, :password)
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_new_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "ユーザ登録に成功しました。"
      redirect_to articles_path
    else
      flash.now[:alert] = "ユーザ登録に失敗しました。"
      render :new
    end
  end

  private
    def user_new_params
      params.require(:user).permit(:name, :email, :password)
    end
end

app/helpers/api/articles_helper.rb
module Api::ArticlesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
    def own_article?(article)
      current_user&.id == article.user_id
    end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_articleform.html.erb
<div class="editor-page">
    <div class="container page">
        <div class="row">
            <div class="col-md-10 offset-md-1 col-xs-12">
                <ul class="error-messages">
                    <% if @article.errors.any? %>
                        <% @article.errors.each do |error| %>
                           <li><%= error.full_message %></li>
                        <% end %>
                    <% end %>
                </ul>
                <%= form_with model: @article, local: true do |form| %>
                    <div class="form-group">
                        <%= form.text_field :title, class: "form-control form-control-lg", placeholder: "Article Title" %>
                    </div>
                    <div class="form-group">
                        <%= form.text_field :about, class: "form-control", placeholder: "What's this article about?" %>
                    </div>
                    <div class="form-group">
                        <%= form.text_area :description, class: "form-control", rows: 8, placeholder: "Write your article (in markdown)" %>
                    </div>
                    <div class="form-group">
                        <input type="text" id="tag_input" class="form-control" placeholder="Enter tag">
                        <div id="tag-list">
                            <% @article.tags.each do |tag| %>
                                <span class="tag-default tag-pill">
                                    <%= tag.name %> <i class="ion-close-round remove-tag"></i>
                                </span>
                            <% end %>
                        </div>
                        <%= form.hidden_field :tag_string, value: @article.tags.map(&:name).join(','), id: 'article_tag_names_hidden' %>
                    </div>
                    <%= form.submit "Publish Article",class: "btn btn-lg pull-xs-right btn-primary" %>
                <% end %>
            </div>
        </div>
    </div>
<% content_for :add_Article_tags_js do %>
  <%= javascript_include_tag "articles_script" %>
<% end %>
</div>

app/views/articles/edit.html.erb
<%= render 'articleform' %>

app/views/articles/index.html.erb
<div class="home-page">
  <div class="banner">
    <div class="container">
      <h1 class="logo-font">conduit</h1>
      <p>A place to share your knowledge.</p>
    </div>
  </div>

  <div class="container page">
    <div class="row">
      <div class="col-md-9">
        <div class="feed-toggle">
          <ul class="nav nav-pills outline-active">
            <li class="nav-item">
              <a class="nav-link" href="">Your Feed</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" href="">Global Feed</a>
            </li>
            <% if logged_in? %>
              <li>
                <%= link_to "create", new_article_path, class: "page-link create-btn" %>
              </li>
            <% end %>
          </ul>
        </div>
        <% if @articles %>
          <% @articles.each do |article| %>
            <div class="article-preview">
              <%= link_to article_path(article), class: "preview-link" do%>
                <h1><%= article.title %></h1>
                <p><%= article.about %></p>
                <p><%= article.user.name %></p>
                <span>Read more...</span>
                <ul class="tag-list">
                  <%# <li class="tag-default tag-pill tag-outline">realworld</li>
                  <li class="tag-default tag-pill tag-outline">implementations</li> %>
                </ul>
              <% end %>
            </div>
          <% end %>
        <% end %>

        <div>
          <%= paginate @articles %>
        </div>
        <!-- <ul >
          <li class="page-item active">
            <a class="page-link" href="">1</a>
          </li>
          <li class="page-item">
            <a class="page-link" href="">2</a>
          </li>
        </ul>  -->

      </div>

      <div class="col-md-3">
        <div class="sidebar">
          <p>Popular Tags</p>

          <div class="tag-list">
            <a href="" class="tag-pill tag-default">programming</a>
            <a href="" class="tag-pill tag-default">javascript</a>
            <a href="" class="tag-pill tag-default">emberjs</a>
            <a href="" class="tag-pill tag-default">angularjs</a>
            <a href="" class="tag-pill tag-default">react</a>
            <a href="" class="tag-pill tag-default">mean</a>
            <a href="" class="tag-pill tag-default">node</a>
            <a href="" class="tag-pill tag-default">rails</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/articles/new.html.erb
<%= render 'articleform' %>

app/views/articles/show.html.erb
<div class="article-page">
    <div class="banner">
        <div class="container">
            <h1><%= @article.title %></h1>
            <div class="info">
                <span class="author">author: <%= @article.user.name %> </span>
            </div>
            <% if own_article?(@article) %>
                <div class="article-meta">
                    <%= button_to "Edit Article", edit_article_path(@article), method: :get, class: "btn btn-sm btn-outline-secondary ion-edit" %>
                    <%= button_to "Delete Article", article_path(@article), method: :delete, class: "btn btn-sm btn-outline-danger ion-trash-a" %>
                </div>
            <% end %>
        </div>
    </div>

    <div class="container page">
        <div class="row article-content">
            <div class="col-md-12">
                <p><%= @article.about %></p>
                <p><%= @article.description %></p>
            </div>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <title>HelloApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="//demo.productionready.io/main.css" />
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "articles", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
</head>

<body>
    <header>
        <nav class="navbar navbar-light">
            <div class="container">
                <a class="navbar-brand" href="/">conduit</a>
                <ul class="nav navbar-nav pull-xs-right">

                <% if logged_in? %>
                    <li class="nav-item">
                        <%= link_to "logout", session_path(session[:user_id]), data: { turbo_method: :delete, data_confirm: "ログアウトします。よろしいでしょうか?" }, class: "nav-link" %> 
                    </li>
                <% else %>
                    <li class="nav-item">
                        <%= link_to "Home", articles_path, class: "nav-link active" %>
                    </li>
                    <li class="nav-item">
                        <%= link_to "Sign in", new_session_path, class: "nav-link" %>
                    </li>
                    <li class="nav-item">
                        <%= link_to "Sign up", new_user_path, class: "nav-link" %>
                    </li>
                <% end %>
                </ul>
            </div>
        </nav>
    </header>
    <div class="error-messages">
        <% if flash[:notice] %>
            <p class="alert alert-success"><%= flash[:notice]%></p>
        <% end %>
        <% if flash[:alert] %>
            <p class="alert alert-danger"><%= flash[:alert]%></p>
        <% end %>
    </div>
    <%= yield %>
    <%= yield :add_Article_tags_js %>
</body>

</html>

app/views/tags/index.html.erb
<h1>Tags#index</h1>
<p>Find me in app/views/tags/index.html.erb</p>

app/views/users/new.html.erb
 <div class="auth-page">
    <div class="container page">
        <div class="row">
            <div class="col-md-6 offset-md-3 col-xs-12">
                <h1 class="text-xs-center">Sign up</h1>
                <p class="text-xs-center">
                    <%= link_to "Already have an acount?", new_session_path, class: "nav-link" %>
                </p>

                <ul class="error-messages">
                     <% if @user.errors.any? %>
                        <% @user.errors.each do |error| %>
                           <li><%= error.full_message %></li>
                        <% end %>
                    <% end %>
                </ul>

                <%= form_with model: @user, local: true do |form| %>
                    <div class="form-group">
                        <%= form.text_field :name, class: "form-control form-control-lg", placeholder: "name"%>
                    </div>
                    <div class="form-group">
                        <%= form.email_field :email, class: "form-control form-control-lg", placeholder: "Email"%>
                    </div>
                    <div class="form-group">
                        <%= form.password_field :password, class: "form-control form-control-lg", placeholder: "Password"%>
                    </div>
                    <%= form.submit "Sign up", class: "btn btn-lg btn-primary pull-xs-right"%>
                <% end %>
            </div>
        </div>
    </div>
</div> 